### PR TITLE
Fixes #63: Remove call to "trans" function in service provider boot

### LINKED ISSUE #63: Laravel Nova is always in English when using this package
**Describe the bug**
I have an installation of Laravel Nova in the same app that I'm using this package and I noticed that Laravel Nova started to be in English after installing this package. I have the translations for Laravel Nova to Brazilian Portuguese. 

**To Reproduce**
1. Install Laravel Nova (hard to reproduce because needs a license)
2. Change the app to a different language
3. Create some translations for this new language
4. Install this package
5. Go to Nova installation and you will see that Laravel Nova is in English

**Expected behavior**
See Laravel Nova in configured language.

**Screenshots**
When this package is installed:
image

If I comment this line in `ReCaptchaServiceProvider`:
image

Then I have it in the correct language:
image

**Environment:**
 - OS and server: Docker image php8.0-apache
 - PHP version 8.0
 - Laravel version 8.68.1
 - Package version 5.0.1

### PR DESCRIPTION
**Pull request by lisotton**

### CODE REVIEW

**Comment by biscolab** [comment]
@lisotton May I ask you why?

**Comment by lisotton** [comment]
@biscolab I explained it here: https://github.com/biscolab/laravel-recaptcha/issues/63

**Comment by biscolab** [comment]
Did you provide a valid translation for `validation.recaptcha`?

**Comment by lisotton** [comment]
Yes, but Laravel Nova was in English, it does not respect what is in the configuration. I found out that removing the `trans` function, it was working as expected.

**Comment by biscolab** [comment]
I can't "just" remove that line without any other test. I have to ensure the compatibility of any other user that already has installed a working package. It could fix your issue but for sure it will add several other unexpected behaviors

**Comment by lisotton** [comment]
But I'm not sure that call `trans` in a `boot` is a good practice. Translation package might not be initialized yet and then the `trans` call will initialize the service without the proper config. Have you tried to reproduce the issue?

**Comment by yapsr** [comment]
Please move the trans() function out of the boot sequence. It is bad practice and breaks Laravel Nova translations.

**Pull request closed without merging**
